CREATE OR REPLACE TRIGGER delete_from_hostel
AFTER DELETE ON STUDENT
FOR EACH ROW
WHEN (OLD.ID > 0)
BEGIN
UPDATE HOSTEL
SET VACANCY=VACANCY+1
WHERE ID=:OLD.HOSTEL_ID;
UPDATE HOSTEL
SET NUMBER_OF_STUDENTS=NUMBER_OF_STUDENTS-1
WHERE ID=:OLD.HOSTEL_ID;
END;
