CREATE OR REPLACE TRIGGER upd_student
AFTER UPDATE ON STUDENT
FOR EACH ROW
WHEN (NEW.ID>0)
DECLARE
tot_rooms NUMBER;
BEGIN
IF :NEW.HOSTEL_ID!=:OLD.HOSTEL_ID THEN
UPDATE HOSTEL
SET VACANCY=VACANCY+1
WHERE ID=:OLD.HOSTEL_ID;
UPDATE HOSTEL
SET NUMBER_OF_STUDENTS=NUMBER_OF_STUDENTS-1
WHERE ID=:OLD.HOSTEL_ID;
UPDATE HOSTEL
SET VACANCY=VACANCY-1
WHERE ID=:NEW.HOSTEL_ID;
UPDATE HOSTEL
SET NUMBER_OF_STUDENTS=NUMBER_OF_STUDENTS+1
WHERE ID=:NEW.HOSTEL_ID;
DELETE FROM ROOM
WHERE STUDENT_ID=:OLD.ID;
SELECT COUNT(*) INTO tot_rooms
FROM ROOM;
tot_rooms:=tot_rooms+1;
INSERT INTO ROOM VALUES(tot_rooms,:NEW.ID,:NEW.HOSTEL_ID);
END IF;
END;
