CREATE OR REPLACE TRIGGER insert_into_hostel
AFTER INSERT ON STUDENT
FOR EACH ROW
WHEN (NEW.ID > 0)
BEGIN
UPDATE HOSTEL
SET VACANCY=VACANCY-1
WHERE ID=:NEW.HOSTEL_ID;
UPDATE HOSTEL
SET NUMBER_OF_STUDENTS=NUMBER_OF_STUDENTS+1
WHERE ID=:NEW.HOSTEL_ID;
END;
