CREATE OR REPLACE TRIGGER insert_prev_into_hostel
BEFORE INSERT ON STUDENT
FOR EACH ROW
WHEN (NEW.ID > 0)
DECLARE
vac NUMBER;
BEGIN
SELECT VACANCY INTO vac
FROM HOSTEL
WHERE ID=:NEW.HOSTEL_ID;
IF vac=0 THEN
RAISE_APPLICATION_ERROR(-20001, 'This hostel is full!');
END IF;
END;
