CREATE TABLE HOSTEL
(
id NUMBER PRIMARY KEY,
name VARCHAR(30),
vacancy NUMBER,
number_of_students NUMBER
);

INSERT INTO HOSTEL VALUES(1,'HOSTEL_A',2,0);
INSERT INTO HOSTEL VALUES(2,'HOSTEL_B',2,0);
INSERT INTO HOSTEL VALUES(3,'HOSTEL_C',2,0);
INSERT INTO HOSTEL VALUES(4,'HOSTEL_D',2,0);
